name: "Secrets variables"
description: "Variable Service"
inputs:
  gcp_project_id:
    description: "ID from project into GCP"
  gcp_env:
    description: "GCP environment (dev, qa, prod)"
  env:
    description: "Environment for using"
  project_name:
    description: "Project Name"
  redis_host:
    description: "Redis Host IP"
  redis_password:
    description: "Redis Password"
  azure_openai_api_key:
    description: "Azure OpenAI Api key"
  azure_openai_version:
    description: "Azure OpenAI API Version"
  azure_instance_name:
    description: "Azure OpenAI Instance Name"
  azure_openai_deployment_name:
    description: "Azure OpenAI Deployment Name"
  azure_openai_endpoint:
    description: "Azure OpenAI Endpoint"
  azure_openai_api_version_o3_mini:
    description: "Azure OpenAI API Version for o3 mini"
  azure_openai_deployment_name_o3_mini:
    description: "Azure OpenAI Deployment Name for o3 mini"
  azure_openai_endpoint_o3_mini:
    description: "Azure OpenAI Endpoint for o3 mini"
  azure_instance_name_o3_mini:
    description: "Azure Instance Name for o3 mini"
  langfuse_secret_key:
    description: "Secret Key for langfuse service"
  langfuse_public_key:
    description: "Public Key for langfuse service"
  langfuse_host:
    description: "Langfuse host url"
runs:
  using: "composite"
  steps:
    - name: conf env
      shell: bash
      run: |
        echo "GCP_ENV=${{ inputs.gcp_env }}" >> .env
        echo "GCP_PROJECT_ID=\"${{ inputs.gcp_project_id }}\"" >> .env
        echo "ENV=\"${{ inputs.gcp_env }}\"" >> .env
        echo "PROJECT_NAME=\"${{ inputs.project_name }}\"" >> .env
        echo "REDIS_HOST=\"${{ inputs.redis_host }}\"" >> .env
        echo "REDIS_PASSWORD=\"${{ inputs.redis_password }}\"" >> .env
        echo "AZURE_OPENAI_API_KEY=\"${{ inputs.azure_openai_api_key }}\"" >> .env
        echo "AZURE_OPENAI_API_VERSION=\"${{ inputs.azure_openai_version }}\"" >> .env
        echo "AZURE_INSTANCE_NAME=\"${{ inputs.azure_instance_name }}\"" >> .env
        echo "AZURE_OPENAI_DEPLOYMENT_NAME=\"${{ inputs.azure_openai_deployment_name }}\"" >> .env
        echo "AZURE_OPENAI_ENDPOINT=\"${{ inputs.azure_openai_endpoint }}\"" >> .env
        echo "AZURE_OPENAI_API_VERSION_o3_MINI=\"${{ inputs.azure_openai_api_version_o3_mini }}\"" >> .env
        echo "AZURE_INSTANCE_NAME_o3_MINI=\"${{ inputs.azure_instance_name_o3_mini }}\"" >> .env
        echo "AZURE_OPENAI_DEPLOYMENT_NAME_o3_MINI=\"${{ inputs.azure_openai_deployment_name_o3_mini }}\"" >> .env
        echo "AZURE_OPENAI_ENDPOINT_o3_MINI=\"${{ inputs.azure_openai_endpoint_o3_mini }}\"" >> .env
        echo "LANGFUSE_SECRET_KEY=\"${{ inputs.langfuse_secret_key }}\"" >> .env
        echo "LANGFUSE_PUBLIC_KEY=\"${{ inputs.langfuse_public_key }}\"" >> .env
        echo "LANGFUSE_HOST=\"${{ inputs.langfuse_host }}\"" >> .env


        ## adding .env to $GITHUB_ENV
        grep -v '^#' .env | while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done
