apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
spec:
  selector:
    app: {{ .Values.config.name }}
  ports:
    - port: 8080
      targetPort: 8080
